### PR TITLE
Exit with non-zero code on cloud commands with error results

### PR DESCRIPTION
**Pull request by emilyrose**

### CODE REVIEW

**Comment by joegoggins** [comment]
Looks good to me. I don't think -1 is possible as a shell exit code, 1 is as good as any for indicating error. As long as you exit non-zero under error conditions, someone relying on the exit code will probably be a happy camper.

**Comment by emilyrose** [comment]
@joegoggins sounds good.

**Comment by dmiddlecamp** [comment]
Hmm, I think it would have been better if we used the existing exit code system, instead of explicitly calling process.exit.  Any command that returns a promise, that rejects on an error will automatically call process.exit(1), yeah?

So instead we could have written:

```
return when.reject("error goes here");
```

which would let things cleanup / wrap up nicely, and would allow the code to be testable and portable inside modules / reused, etc.  :)

**Comment by emilyrose** [comment]
@dmiddlecamp ah! that's good to know. My inexperience with `when` is showing here. I will try it out with reject! thanks! :smile_cat:

**Comment by dmiddlecamp** [comment]
No worries, to be fair, the convention wasn't followed everywhere :)

**Comment by emilyrose** [comment]
so I fixed this with #142, but supplying a string to `when.reject()` didn't have any observable effect (no change in exit code, no stdout without console.log), so I left it out.

**Pull request merged**
